### ISSUE TITLE
Unknown error for ligand

### ISSUE THREAD

**Issue by eneas77** [Isra3l/ligpargen#10]
Hi,

WHen submitting the following pdb, LigParGen crashes with following error:

Traceback (most recent call last):
  File "/home/e77/.conda/envs/ligpargen/bin/ligpargen", line 33, in <module>
    sys.exit(load_entry_point('LigPargen', 'console_scripts', 'ligpargen')())
  File "/home/e77/ligpargen/ligpargen/ligpargen.py", line 496, in main
    molname=args.molname, workdir= args.path, debug= args.debug)
  File "<string>", line 17, in __init__
  File "/home/e77/ligpargen/ligpargen/ligpargen.py", line 192, in __post_init__
    moleculeA = Molecule.fromBOSS(zmatName, outFile, pdbFile, moleculeA.shiftX, moleculeA.shiftY, moleculeA.shiftZ)
  File "/home/e77/ligpargen/ligpargen/topology/Molecule.py", line 149, in fromBOSS
    anglesVariable, anglesAdditional = cls._getAngles(zmatData, outFileData, atoms, serial2IndexAtoms)
  File "/home/e77/ligpargen/ligpargen/topology/Molecule.py", line 579, in _getAngles
    atomA = atoms[serial2IndexAtoms[int(angleF[0])]]
ValueError: invalid literal for int() with base 10: 'Force'

ANy ideas of the issue? Tried with server version and again is happening...

Thank you very much,

E77

[lba0000025813_lig_old.txt](https://github.com/Isra3l/ligpargen/files/8926420/lba0000025813_lig_old.txt)

**Comment by Isra3l** [comment]
Dear eneas77,

I’ve attempted to reproduce your issue, but I cannot. In my case, LigParGen completes successfully. It’s likely that this issue has been resolved in one of the recent updates of BOSS or LigParGen.

I recommend ensuring that you are using the latest versions of both.

Best,

Israel

**Comment by eneas77** [comment]
Fucking awesome timing... Once published, the hell with the code, idm anymore...
