### ISSUE TITLE
Cannot run charge algorithm CM1A-LBCC

### ISSUE THREAD

**Issue by BJWiley233** [Isra3l/ligpargen#13]
Hi,

When testing with small molecule this works:
```
$ ligpargen -i ribociclib.poltype.opt.sdf -n ribociclib -p ribociclib -r 6ZZ -c 0 -o 0 -cgen CM1A
LigParGen finished succesfully!
```
but using `CM1A-LBCC` gives traceback
```
$ ligpargen -i ribociclib.poltype.opt.sdf -n ribociclib -p ribociclib -r 6ZZ -c 0 -o 0 -cgen CM1A-LBCC
Traceback (most recent call last):
  File "/opt/conda/envs/py37/bin/ligpargen", line 33, in <module>
    sys.exit(load_entry_point('LigPargen', 'console_scripts', 'ligpargen')())
  File "/opt/ligpargen/ligpargen/ligpargen.py", line 496, in main
    molname=args.molname, workdir= args.path, debug= args.debug)
  File "<string>", line 17, in __init__
  File "/opt/ligpargen/ligpargen/ligpargen.py", line 192, in __post_init__
    moleculeA = Molecule.fromBOSS(zmatName, outFile, pdbFile, moleculeA.shiftX, moleculeA.shiftY, moleculeA.shiftZ)
  File "/opt/ligpargen/ligpargen/topology/Molecule.py", line 141, in fromBOSS
    atoms, numberOfStructuralDummyAtoms = cls._getAtoms(cls, zmatData, pdbfile)
  File "/opt/ligpargen/ligpargen/topology/Molecule.py", line 460, in _getAtoms
    atomsLines = re.search(r'BOSS(.*?)Geometry', zmatData, re.DOTALL).group().splitlines()[1:-1]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Isra3l** [comment]
Hey BJ,

For CM1A-LBCC you need to use BOSS5.0. You should send an email to Prof. Jorgensen and request an executable of BOSS5.0 because the default downloadable BOSS version on the website is BOSS4.9.

Best,

Israel

**Comment by BJWiley233** [comment]
Yes sorry should have indicated afterwards I saw your post earlier regarding 5.0 but forgot to update/close ticket.  Thanks.
