### ISSUE TITLE
Failing installation

### ISSUE THREAD

**Issue by ricalessandri** [Isra3l/ligpargen#7]
Hi, I've installed with the following:
```
conda create --name ligpargen python=3.7
conda activate ligpargen
[obtained BOSS from Jorgensen  http://zarbi.chem.yale.edu/software.html]
[echo "export BOSSdir=/XXX/XXX/XXX/bin/boss" >> ~/.bashrc] where XXX is my path 
conda install -c rdkit rdkit
conda install -c conda-forge openbabel
```

But then, running:
```
cd ligpargen;python -m unittest test_ligpargen/test_ligpargen.py
```
gives:
```
....................F..
======================================================================
FAIL: test_openMM_outputs (test_ligpargen.test_ligpargen.test_ligpargen)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/XXX/XXX/bin/ligpargen/test_ligpargen/test_ligpargen.py", line 571, in test_openMM_outputs
    self.assertEqual(benzene_xml, benzene_xml_golden)
AssertionError: Lists differ: ['<!-[261 chars]class="C800" element="C" mass="12.011"/>', '<T[13538 chars]ld>'] != ['<!-[261 chars]class"C800" element="C" mass="12.011"/>', '<Ty[13527 chars]ld>']

First differing element 6:
'<Type name="opls_800" class="C800" element="C" mass="12.011"/>'
'<Type name="opls_800" class"C800" element="C" mass="12.011"/>'

Diff is 16297 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 23 tests in 0.083s

FAILED (failures=1)
```

And running:
```
ligpargen -s 'c1ccc(cc1)O'
```
gives:
```
Traceback (most recent call last):
  File "/XXX/.conda/envs/ligpargen/bin/ligpargen", line 33, in <module>
    sys.exit(load_entry_point('LigPargen', 'console_scripts', 'ligpargen')())
  File "/XXX/XXX/bin/ligpargen/ligpargen/ligpargen.py", line 496, in main
    molname=args.molname, workdir= args.path, debug= args.debug)
  File "<string>", line 17, in __init__
  File "/XXX/XXX/bin/ligpargen/ligpargen/ligpargen.py", line 192, in __post_init__
    moleculeA = Molecule.fromBOSS(zmatName, outFile, pdbFile, moleculeA.shiftX, moleculeA.shiftY, moleculeA.shiftZ)
  File "/XXX/XXX/bin/ligpargen/ligpargen/topology/Molecule.py", line 141, in fromBOSS
    atoms, numberOfStructuralDummyAtoms = cls._getAtoms(cls, zmatData, pdbfile)
  File "/XXX/XXX/bin/ligpargen/ligpargen/topology/Molecule.py", line 460, in _getAtoms
    atomsLines = re.search(r'BOSS(.*?)Geometry', zmatData, re.DOTALL).group().splitlines()[1:-1]
AttributeError: 'NoneType' object has no attribute 'group'
```

Any help appreciated :-)

**Comment by Isra3l** [comment]
Hey,

I have been checking and I can not reproduce your problem. Probably, it is because you are using BOSS4.9 and the default charge model (CM1A-LBCC) requires BOSS5.0. I suggest you send an email to Bill Jorgensen and ask him to download BOSS5.0. Other people had similar issues and they fixed them with BOSS5.0.

It should fix your problems. I hope it works

Best,

Israel
